### ISSUE TITLE
DaprClient in JS throws DaprClient throws error saying ECONNREFUSED under load condition

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/js-sdk#123]
## Expected Behavior

We are using DaprClient to publish message to kafka using kafka pubsub.  
We are receiving http request in our application via dapr side car and in the application we are publishing the message to kafka pub sub using DaprClient. DaprClient should publish the message to kafka pub sub when rate of publishing to kafka is increased. 

## Actual Behavior
DaprClient throws error when the rate at which we publish the message increases. 

We get an error from DarpClient
ERROR 14:43:36:777 error publishing topic through dapr:  FetchError: request to http://localhost:3500/v1.0/publish/kafka-pubsub/request-topic failed, reason: connect ECONNREFUSED 127.0.0.1:3500
== APP ==     at ClientRequest.<anonymous> 

When the rate at which we are publishing the message to kafka pub sub increase than DaprClient throws error saying connection refused.

## Steps to Reproduce the Problem

We are using DaprCLient and publishing using below

```javascript
 async publishMessage(topic: string, message: PubSubMessage): Promise<void> {
    try {
      await this.client.pubsub.publish(this.pubsubName, topic, message);
    } catch (error: any) {
      logger.error("error publishing topic through dapr: ", error);
    }
  }
```

yaml for binding is

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "localhost:9092"
  - name: consumerGroup # Optional. Used for input bindings.
    value: "group1"
  - name: clientID # Optional. Used as client tracing ID by Kafka brokers.
    value: "my-dapr-app-id"
  - name: authRequired # Required.
    value: "false"
 ```

It is running on Mac M1
