### ISSUE TITLE
Azure IoT Hub not receiving any messages through Bindings or PubSub

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#267]
## Expected Behavior

1. Create Azure IoT Hub
2. Copy Built-In EventHub Connection String
3. Configure it in the components as shown below
4. Use it through PubSub / Bindings

Being able to get the messages of IoT Hub through the built-in Event Hub endpoint

## Actual Behavior

Not seeing any messages

## Steps to Reproduce the Problem

**component-pubsub.yaml**

```yaml
# https://docs.dapr.io/reference/components-reference/supported-bindings/eventhubs/
# https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#subscribing-to-azure-iot-hub-events
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: component-pubsub
  namespace: default
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString      # Azure EventHubs connection string
    value: "CONNECTION_STRING"
  - name: consumerGroup         # EventHubs consumer group
    value: "$Default"
  - name: storageAccountName    # Azure Storage Account Name
    value: "NAME"
  - name: storageAccountKey     # Azure Storage Account Key
    value: "KEY"
  - name: storageContainerName  # Azure Storage Container Name
    value: "NAME"
```

**component-binding.yaml**

```yaml
# https://docs.dapr.io/reference/components-reference/supported-bindings/eventhubs/
# https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#subscribing-to-azure-iot-hub-events
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: component-binding
  namespace: default
spec:
  type: bindings.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString      # Azure EventHubs connection string
    value: "CONNECTION_STRING"
  - name: consumerGroup         # EventHubs consumer group
    value: "$Default"
  - name: storageAccountName    # Azure Storage Account Name
    value: "NAME"
  - name: storageAccountKey     # Azure Storage Account Key
    value: "KEY"
  - name: storageContainerName  # Azure Storage Container Name
    value: "NAME"
  - name: partitionID
    value: 0
```

**index.ts**

```javascript
import { CommunicationProtocolEnum, DaprClient, DaprServer } from "@dapr/dapr";
import Config from "./config";
import { logger } from "./utils/Logger";


// Create a Server (will subscribe) and Client (will publish)
async function main() {
  const server = new DaprServer();

  // Initialize the server to subscribe (listen)
  await server.pubsub.subscribe("component-pubsub", "iothub-name", async (data: any) => {
    console.log(`PubSub Received: ${JSON.stringify(data)}`);
  });
  await server.binding.receive("component-binding", async (data: any) => {
    console.log(`Binding Received: ${JSON.stringify(data)}`);
  });
  await server.start();
}

main().catch(e => console.error(e));
```

Output being shown by Dapr (trying PubSub and Binding):

```
DEBU[0003] loading component. name: binding-azure-eventhub, type: bindings.azure.eventhubs/v1  app_id=stream-processor instance=THE-BEAST scope=dapr.runtime type=log ver=1.7.3
INFO[0003] successful init for output binding binding-azure-eventhub (bindings.azure.eventhubs/v1)  app_id=stream-processor instance=THE-BEAST scope=dapr.runtime type=log ver=1.7.3
INFO[0003] successful init for input binding binding-azure-eventhub (bindings.azure.eventhubs/v1)  app_id=stream-processor instance=THE-BEAST scope=dapr.runtime type=log ver=1.7.3
INFO[0003] component loaded. name: binding-azure-eventhub, type: bindings.azure.eventhubs/v1  app_id=stream-processor instance=THE-BEAST scope=dapr.runtime type=log ver=1.7.3
DEBU[0003] loading component. name: pubsub-azure-eventhub, type: pubsub.azure.eventhubs/v1  app_id=stream-processor instance=THE-BEAST scope=dapr.runtime type=log ver=1.7.3
```

App shows also that it is registering the PubSub

```
== APP == {"level":30,"time":1652951616106,"pid":5622,"hostname":"THE-BEAST","name":"stream-processor","msg":"[Dapr API][PubSub] Registered 1 PubSub Subscriptions"}
```
