### ISSUE TITLE
Workflow example is not working.

### ISSUE THREAD

**Issue by sce9sc** [dapr/js-sdk#549]
## Expected Behavior

I run the workflow example but it did not work . The example seems incomplete. 

## Actual Behavior

components folder is missing and there is not "OrderProcessingWorkflow"

## Steps to Reproduce the Problem

run the example as described. 

PS One of the best projects I ever found . Thanks

**Comment by sce9sc** [comment]
After adding components folder and a redis config I got 

```
== APP ==
== APP == > dapr-example-workflow@1.0.0 start
== APP == > npm run build && node dist/index.js
== APP ==
== APP ==
== APP == > dapr-example-workflow@1.0.0 build
== APP == > rimraf ./dist && tsc
== APP ==
== APP == 2023-10-31T19:24:41.609Z INFO [HTTPClient, HTTPClient] Sidecar Started
== APP == 2023-10-31T19:24:51.621Z ERROR [HTTPClient, Workflow] Error starting workflow instance: {"error":"Bad Request","error_msg":"{\"errorCode\":\"ERR_WORKFLOW_COMPONENT_NOT_FOUND\",\"message\":\"workflow component 'dapr' does not exist\"}","status":400}
== APP == Error: {"error":"Bad Request","error_msg":"{\"errorCode\":\"ERR_WORKFLOW_COMPONENT_NOT_FOUND\",\"message\":\"workflow component 'dapr' does not exist\"}","status":400}
== APP ==     at HTTPClient.<anonymous> (C:\Users\Stavros\Documents\work\dapr-workflow\node_modules\@dapr\dapr\implementation\Client\HTTPClient\HTTPClient.js:172:23)
== APP ==     at Generator.next (<anonymous>)
== APP ==     at fulfilled (C:\Users\Stavros\Documents\work\dapr-workflow\node_modules\@dapr\dapr\implementation\Client\HTTPClient\HTTPClient.js:40:58)
== APP ==     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
The App process exited with error code: exit status 1
```

The config I used was 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state-redis
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
```
